[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jdu"
version = "0.0.3"
dependencies = [
    "requests",
    "aiohttp",
    "jarvis_db @ git+https://github.com/PickAim/jarvis_db.git@dev",
]